export const makes=['Acura','Audi','BMW','Buick','Cadillac','Chevrolet','Chrysler','Dodge','Ford','GMC','Honda','Hyundai','Infiniti','Isuzu','Jaguar','Jeep','Kia','Land Rover','Lexus','Lincoln','Mazda','Mercedes-Benz','Mitsubishi','Nissan','Pontiac','Porsche','Saab','Saturn','Subaru','Suzuki','Toyota','Volkswagen','Volvo'];
export const categories=[{slug:'engine',name:'Used Engine',icon:'⚙️',text:'Quality-tested gasoline, diesel and hybrid engines, backed by warranty.'},{slug:'transmission',name:'Used Transmission',icon:'🔩',text:'Automatic, manual, CVT and electric transmissions for major makes.'},{slug:'axle-assembly',name:'Axle Assembly',icon:'🛞',text:'Dependable OEM axle assemblies inspected for fit and performance.'},{slug:'transfer-case',name:'Transfer Case',icon:'⛓️',text:'OEM transfer cases for dependable four-wheel and all-wheel drive.'},{slug:'headlight',name:'Headlight',icon:'💡',text:'Original headlamp assemblies with verified connectors and fitment.'},{slug:'tail-light',name:'Tail Light',icon:'🔴',text:'OEM tail lamps for a factory-quality replacement.'}];
export const infoPages:Record<string,{title:string;description:string;body:string[]}>= {
'about-us':{title:'About Supreme Autoparts',description:'A trusted Nairobi supplier of quality auto parts.',body:['Supreme Autoparts connects drivers, repair shops and automotive businesses with quality parts from our Nairobi location and supplier network.','Every request is reviewed for vehicle fitment. Our team focuses on clear communication, fair pricing and dependable delivery from quote through after-sales support.','Visit us at Midax Plaza on Kangundo Road or contact us by call or WhatsApp.']},
'shipping-payment-policy':{title:'Delivery & Payment',description:'Kenya delivery and secure payment information.',body:['We arrange delivery across Kenya. Charges and estimated timing depend on the component size and destination and are confirmed before payment.','Tracking or courier details are shared as soon as the order is dispatched. Inspect delivered items promptly and contact our team if there is any concern.','Secure online payments are processed through Pesapal or TransactPay.ai. Never send payment to an individual or an unverified account.']},
'warranty-and-return':{title:'Warranty & Returns',description:'Straightforward warranty coverage and return guidance.',body:['Engines and transmissions include the warranty stated on the final invoice. Coverage begins on the delivery date and applies to the component supplied.','Contact support before returning any item. Approved returns must be shipped in substantially the same condition and packaging in which they arrived.','Labor, towing, fluids and incidental expenses are not covered unless explicitly stated in writing. Full terms appear on your order documentation.']},
'privacy-policy':{title:'Privacy Policy',description:'How Supreme Autoparts handles personal information.',body:['We collect information you provide when requesting a quote, placing an order, tracking a shipment or contacting support.','We use this information to provide services, prevent fraud, improve the website and communicate about your request. We do not sell personal information.','You may request access, correction or deletion by contacting calvin@supremeautoparts.co.ke.']},
'cookie-policy':{title:'Cookie Policy',description:'How cookies support site functionality and analytics.',body:['Essential cookies keep forms, preferences and security features working. Optional analytics help us understand aggregate site usage.','You can manage non-essential cookies through your browser settings. Disabling some cookies may limit site functionality.']},
'terms':{title:'Terms & Conditions',description:'Terms governing use of the Supreme Autoparts website.',body:['By using this website, you agree to provide accurate vehicle and contact information and to review order details before payment.','Availability, pricing and delivery estimates may change until an order is confirmed. Product images may be representative of the part type.','These terms are governed by the laws of Kenya. Contact us with any question before placing an order.']}
};
