import {writeFile} from 'node:fs/promises';
const live='https://www.supremeautoparts.co.ke';const reference='https://partscentral.us';
const paths=['/','/auto-parts/','/engine/','/transmission/','/contact-us/','/about-us/','/shipping-payment-policy/','/warranty-and-return/','/privacy-policy/','/terms-and-conditions/','/faq/','/track-order/','/submit-ticket/','/testimonials/','/blog/','/shop/','/shop/?s=Toyota&post_type=product','/product/toyota-engine-assembly/','/product-category/engine/','/cart/','/checkout/','/my-account/','/used-auto-parts/toyota/','/used-auto-parts/ford/'];
const forbidden=[/Parts\s*Central/ig,/partscentral\.us/ig,/\(888\)\s*338-2540/g,/Evanston/ig,/support@partscentral\.us/ig];
async function inspect(base,path){const started=performance.now();try{const response=await fetch(base+path,{redirect:'follow',signal:AbortSignal.timeout(30000)});const html=await response.text();const title=html.match(/<title[^>]*>(.*?)<\/title>/is)?.[1]?.replace(/<[^>]+>/g,'').trim()||'';const description=html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||'';const links=[...html.matchAll(/href=["']([^"'#]+)["']/gi)].map(match=>match[1]);return{path,url:response.url,status:response.status,timeMs:Math.round(performance.now()-started),bytes:Buffer.byteLength(html),title,description,hasSupreme:/Supreme Autoparts/i.test(html),hasPhone:/0714\s*498\s*451|\+254714498451/.test(html),hasEmail:/calvin@supremeautoparts\.co\.ke/i.test(html),hasAddress:/Midax Plaza/i.test(html),forbidden:forbidden.flatMap(pattern=>html.match(pattern)||[]),links:[...new Set(links)]};}catch(error){return{path,status:0,error:String(error),timeMs:Math.round(performance.now()-started),links:[]}}}
const liveResults=[];for(let i=0;i<paths.length;i+=5)liveResults.push(...await Promise.all(paths.slice(i,i+5).map(path=>inspect(live,path))));
const referenceResults=[];for(const path of ['/','/auto-parts','/engine','/transmission','/contact-us','/about-us'])referenceResults.push(await inspect(reference,path));
const home=liveResults[0];const internal=(home.links||[]).map(link=>{try{return new URL(link,live)}catch{return null}}).filter(url=>url&&url.origin===new URL(live).origin).map(url=>url.pathname+url.search).slice(0,150);const linkResults=[];for(let i=0;i<internal.length;i+=10)linkResults.push(...await Promise.all(internal.slice(i,i+10).map(path=>inspect(live,path))));
const report={generatedAt:new Date().toISOString(),live,reference,summary:{routesChecked:liveResults.length,routeErrors:liveResults.filter(item=>item.status<200||item.status>=400).length,brandingLeaks:liveResults.reduce((sum,item)=>sum+(item.forbidden?.length||0),0),homeLinksChecked:linkResults.length,brokenHomeLinks:linkResults.filter(item=>item.status>=400||item.status===0).length,medianLiveMs:liveResults.map(item=>item.timeMs).sort((a,b)=>a-b)[Math.floor(liveResults.length/2)]},liveResults,referenceResults,brokenHomeLinks:linkResults.filter(item=>item.status>=400||item.status===0)};await writeFile('qa-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary,null,2));
